# Generated by Django 5.0.3 on 2024-04-24 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account_reset_password_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='status',
        ),
    ]
