# Generated by Django 5.0.1 on 2024-03-27 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_account_groups_account_is_staff_account_is_superuser_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='surname_contact',
            new_name='address',
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
