# Generated by Django 5.0.3 on 2024-05-01 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customers_id_alter_orders_id_alter_products_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='statues_status_id',
            field=models.CharField(max_length=100),
        ),
    ]
