# Generated by Django 5.0.3 on 2024-05-01 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_orders_statues_status_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='seller',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
