# Generated by Django 5.0.3 on 2024-05-01 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customers_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='custumers_addresses',
            name='custumer_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customers'),
            preserve_default=False,
        ),
    ]
