# Generated by Django 5.0.3 on 2024-05-02 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_custumers_addresses_custumer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.customers'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Customers_has_customers_addresses',
        ),
    ]
