# Generated by Django 5.0.3 on 2024-05-02 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_orders_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_has_orders',
            name='quantity',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
