# Generated by Django 5.0.3 on 2024-05-11 10:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_orders_messagetoseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='status_history',
            name='id_order',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.orders'),
            preserve_default=False,
        )
    ]
