# Generated by Django 5.0.3 on 2024-05-11 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_status_history_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status_history',
            name='who_changed',
        ),
        migrations.RunSQL('''
            DELIMITER //

            CREATE TRIGGER update_order_status_history
            AFTER UPDATE ON app_orders
            FOR EACH ROW
            BEGIN
                IF OLD.statues_status_id != NEW.statues_status_id THEN
                    INSERT INTO app_status_history (date_of_change, status, id_order_id)
                    VALUES (NOW(), NEW.statues_status_id, NEW.id);
                END IF;
            END;

            //

            DELIMITER ;

        ''')
    ]
