# Generated by Django 5.0.3 on 2024-05-15 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_remove_status_history_who_changed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='accounts_account_id',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='attachment',
        ),
        migrations.RemoveField(
            model_name='contacts',
            name='customers_customer_id',
        ),
        migrations.AddField(
            model_name='contacts',
            name='account_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_as_account', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='answer_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='created_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='contacts',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='contacts_as_owner', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contacts',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='report_description',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='report_title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='ContactChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(max_length=300, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_chat_as_account', to=settings.AUTH_USER_MODEL)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_chat_as_contact', to='app.contacts')),
            ],
        ),
    ]
