# Generated by Django 5.0.3 on 2024-05-15 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_contactchat_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactchat',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
