# Generated by Django 5.0.3 on 2024-05-23 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_alter_contactchat_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actions',
        ),
        migrations.DeleteModel(
            name='Statues',
        ),
    ]
