# Generated by Django 5.0.4 on 2024-04-15 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produkty', '0002_kategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='kategoy',
        ),
        migrations.AddField(
            model_name='products',
            name='kategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Produkty.kategories'),
        ),
    ]
